version: 2

sources:
  - name: source_test
    database: SNOWFLAKE_SAMPLE_DATA
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: created_on

    tables:
      - name: CALL_CENTER
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
